services:
  jenkins:
    container_name: jenkins
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: --prefix=/jenkins
    volumes:
      - ../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
