# docker-compose-resource.yml
services:
  nginx:
    container_name: reverse
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - /etc/letsencrypt/live/i11e105.p.ssafy.io:/etc/letsencrypt/live/i11e105.p.ssafy.io 

networks:
  mynetwork:
    external: true
