spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # 카카오 클라이언트 ID
            client-secret: ${KAKAO_CLIENT_SECRET} # 카카오 클라이언트 시크릿
            redirect-uri: ${KAKAO_REDIRECT_URI} # 카카오 리다이렉트 URI
            authorization-grant-type: authorization_code # 인증 유형
            client-authentication-method: client_secret_post # 클라이언트 인증 방법
            scope:
              - account_email # 요청할 권한: 이메일
              - talk_message # 요청할 권한: 카카오톡 메시지
            client-name: kakao # 클라이언트 이름

        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: id # 사용자 이름 속성